# Generated by Django 4.2.7 on 2023-11-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_info_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='sex',
            field=models.CharField(default='M', max_length=10),
        ),
    ]
