# Generated by Django 4.2.7 on 2023-11-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0005_info_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('programming_preference', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
